import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const products = [
  {
    name: "Wireless Headphones Pro",
    description: "Premium noise-cancelling wireless headphones with 30-hour battery life and comfortable over-ear cushions.",
    price: 299.99,
    category: "Electronics",
    stock: 50,
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
    condition: "New",
    conditionRating: 10,
    weight: 0.35,
    length: 20,
    width: 18,
    height: 9,
    pricingFormat: "Fixed Price",
    quantity: 50,
    shippingMethod: "Standard Shipping",
    country: "United States",
    city: "New York",
    domesticReturns: true,
    internationalReturns: false,
  },
  {
    name: "Minimalist Leather Watch",
    description: "Classic minimalist watch with genuine leather strap and sapphire crystal glass face.",
    price: 189.99,
    category: "Accessories",
    stock: 30,
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400",
    condition: "New",
    conditionRating: 10,
    weight: 0.08,
    pricingFormat: "Fixed Price",
    quantity: 30,
    shippingMethod: "Express Shipping",
    country: "United Kingdom",
    city: "London",
    domesticReturns: true,
    internationalReturns: true,
  },
  {
    name: "Ergonomic Office Chair",
    description: "Fully adjustable ergonomic chair designed for long work sessions. Lumbar support and breathable mesh.",
    price: 449.99,
    category: "Furniture",
    stock: 20,
    imageUrl: "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=400",
    condition: "New",
    conditionRating: 9,
    weight: 12.5,
    length: 70,
    width: 65,
    height: 120,
    pricingFormat: "Fixed Price",
    quantity: 20,
    shippingMethod: "Freight Overland Items",
    country: "United States",
    city: "Los Angeles",
    domesticReturns: true,
    internationalReturns: false,
  },
  {
    name: "Mechanical Keyboard",
    description: "Compact TKL mechanical keyboard with RGB backlight and blue switches. Great for typing and gaming.",
    price: 129.99,
    category: "Electronics",
    stock: 75,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
    condition: "New",
    conditionRating: 10,
    weight: 0.95,
    length: 36,
    width: 13,
    height: 4,
    pricingFormat: "Fixed Price",
    quantity: 75,
    shippingMethod: "Standard Shipping",
    country: "United States",
    city: "San Francisco",
    domesticReturns: true,
    internationalReturns: true,
  },
  {
    name: "Running Shoes",
    description: "Lightweight breathable running shoes with advanced cushioning technology and anti-slip soles.",
    price: 89.99,
    category: "Footwear",
    stock: 100,
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
    condition: "New",
    conditionRating: 10,
    weight: 0.28,
    pricingFormat: "Fixed Price",
    quantity: 100,
    shippingMethod: "Standard Shipping",
    country: "Canada",
    city: "Toronto",
    domesticReturns: true,
    internationalReturns: false,
  },
  {
    name: "Smart Water Bottle",
    description: "Tracks hydration and keeps beverages at optimal temperature for 24 hours with LED reminders.",
    price: 49.99,
    category: "Lifestyle",
    stock: 60,
    imageUrl: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400",
    condition: "New",
    conditionRating: 9,
    weight: 0.32,
    length: 8,
    width: 8,
    height: 26,
    pricingFormat: "Fixed Price",
    quantity: 60,
    shippingMethod: "Standard Shipping",
    country: "United States",
    city: "Chicago",
    domesticReturns: true,
    internationalReturns: true,
  },
  {
    name: "4K Webcam",
    description: "Ultra-sharp 4K webcam with built-in ring light, autofocus, and noise cancellation microphone.",
    price: 199.99,
    category: "Electronics",
    stock: 40,
    imageUrl: "https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=400",
    condition: "New",
    conditionRating: 10,
    weight: 0.18,
    pricingFormat: "Fixed Price",
    quantity: 40,
    shippingMethod: "Express Shipping",
    country: "Germany",
    city: "Berlin",
    domesticReturns: true,
    internationalReturns: true,
  },
  {
    name: "Yoga Mat Premium",
    description: "Non-slip natural rubber yoga mat with alignment lines, carrying strap and eco-friendly materials.",
    price: 79.99,
    category: "Sports",
    stock: 90,
    imageUrl: "https://images.unsplash.com/photo-1601925228184-9d59f68e0fbe?w=400",
    condition: "New",
    conditionRating: 10,
    weight: 1.5,
    length: 183,
    width: 61,
    height: 0.6,
    pricingFormat: "Fixed Price",
    quantity: 90,
    shippingMethod: "Standard Shipping",
    country: "Australia",
    city: "Sydney",
    domesticReturns: true,
    internationalReturns: false,
  },
];

async function main() {
  console.log("🌱 Seeding database...");

  await prisma.product.deleteMany();

  for (const product of products) {
    await prisma.product.create({ data: product });
  }

  console.log(`✅ Seeded ${products.length} products`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
